
import React from 'react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';

const HeroSection: React.FC = () => {
  return (
    <section className="bg-gradient-to-br from-primary-100 via-white to-primary-100 py-16 md:py-24">
      <div className="container mx-auto px-4 md:px-6">
        <div className="flex flex-col md:flex-row items-center">
          <div className="md:w-1/2 md:pr-12">
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-gray-900 mb-4">
              Generate SEO Titles, Descriptions & Tags with AI – <span className="text-primary-500">Instantly!</span>
            </h1>
            <p className="text-xl text-gray-700 mb-8">
              Boost your YouTube rankings and views with powerful SEO content generated by AI. Perfect for creators who want to grow their channel.
            </p>
            <div className="flex flex-col sm:flex-row gap-4">
              <Button asChild className="bg-primary-500 hover:bg-primary-600 text-white py-6 px-8 text-lg">
                <Link to="/generator">Try Now for Free</Link>
              </Button>
              <Button asChild variant="outline" className="border-primary-500 text-primary-500 hover:bg-primary-100 py-6 px-8 text-lg">
                <Link to="/pricing">View Pricing</Link>
              </Button>
            </div>
          </div>
          <div className="md:w-1/2 mt-12 md:mt-0">
            <div className="relative">
              <div className="absolute -top-6 -left-6 w-full h-full bg-primary-200 rounded-lg"></div>
              <div className="absolute -bottom-6 -right-6 w-full h-full bg-primary-300 rounded-lg"></div>
              <div className="relative bg-white p-6 rounded-lg shadow-lg border border-gray-200">
                <div className="p-4 bg-gray-50 rounded-md border border-gray-200 mb-4">
                  <div className="flex items-center mb-3">
                    <div className="h-3 w-3 rounded-full bg-red-400 mr-2"></div>
                    <div className="h-3 w-3 rounded-full bg-yellow-400 mr-2"></div>
                    <div className="h-3 w-3 rounded-full bg-green-400"></div>
                  </div>
                  <div className="bg-white border border-gray-200 rounded-md p-3">
                    <p className="text-sm text-gray-500 mb-2">Input:</p>
                    <p className="text-gray-800 font-medium">How to start a successful YouTube channel in 2025</p>
                  </div>
                </div>
                <div className="p-4 bg-primary-100 rounded-md border border-primary-200">
                  <p className="text-sm text-primary-700 mb-2">Output:</p>
                  <div className="space-y-3">
                    <div>
                      <p className="text-xs text-gray-500">🎯 TITLE</p>
                      <p className="text-gray-900 font-medium">HOW TO START a YOUTUBE CHANNEL in 2025 (Complete Beginner's Guide)</p>
                    </div>
                    <div>
                      <p className="text-xs text-gray-500">📝 DESCRIPTION</p>
                      <p className="text-gray-700 text-sm">Want to start a YouTube channel in 2025 but don't know where to begin? This step-by-step guide covers everything you need: equipment, niche selection, content planning...</p>
                    </div>
                    <div>
                      <p className="text-xs text-gray-500">🔖 TAGS</p>
                      <div className="flex flex-wrap gap-1">
                        <span className="bg-primary-200 text-primary-700 text-xs px-2 py-1 rounded">youtube tutorial</span>
                        <span className="bg-primary-200 text-primary-700 text-xs px-2 py-1 rounded">start youtube channel</span>
                        <span className="bg-primary-200 text-primary-700 text-xs px-2 py-1 rounded">youtube 2025</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default HeroSection;
